### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by imayoda** [moononournation/ArduinoVNC#1]
Dear moononournation,

I was able to successfully implement the example with a 240x240 GC9A01 lcd.
May I ask you if there are plans to update this modified library code in order to reflect recent changes in master project ?? (eg: xyoffset, maxfps, etc)

Thank you and sorry for bothering :)

**Comment by moononournation** [comment]
it's ok, you can raise a merge request for it.

**Comment by imayoda** [comment]
I'm sure there's a misunderstanding.. I did not a single line modification to this code :blush: , only installed it successfully in combination Arduino_GFX.
I was asking if you plan to sync with ArduinoVNC(links2004) as this adapted library is more than one year beyond.
Shouldn't you rebase ? (sorry, a git rookie here)  
kind regards

**Comment by moononournation** [comment]
My previous project target is adding ZRLE compress method and it is done. As you mentioned, the main branch still active development. I feel free for your contribution to make my code merge into the main branch.
